server:
  port: 8080
spring:
  application:
    name: app
springdoc:
  api-docs:
    path: /openapi
  swagger-ui:
    path: /openapi/ui
management:
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      base-path: /management
      exposure:
        include: info,health,metrics,prometheus
info:
  name: ${spring.application.name}
  profiles: ${spring.profiles.active}
