name: ci-release
on:
  release:
    types:
    - created
jobs:
  release:
    runs-on: ubuntu-20.04
    env:
      APP_VERSION: ${{ github.event.release.tag_name }}
    steps:
    - uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: adopt
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/cache@v2
      with:
        path: |
          ~/.m2/repository
        key: ${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
    - name: mvn
      run: |-
        mvn versions:set \
        --batch-mode \
        --file ./pom.xml \
        --settings ./settings.xml \
        --define newVersion="${APP_VERSION}"
        mvn clean deploy \
        --batch-mode \
        --file ./pom.xml \
        --settings ./settings.xml \
        --define app.packages.username="${APP_PACKAGES_USERNAME}" \
        --define app.packages.password="${APP_PACKAGES_PASSWORD}"
      env:
        APP_PACKAGES_USERNAME: ${{ github.actor }}
        APP_PACKAGES_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
    - name: docker
      run: |-
        echo "${APP_PACKAGES_PASSWORD}" | docker login "${APP_PACKAGES_URL}" \
        --username "${APP_PACKAGES_USERNAME}" \
        --password-stdin
        docker build . \
        --file ./Dockerfile \
        --tag "${APP_PACKAGES_URL}:latest" \
        --tag "${APP_PACKAGES_URL}:${APP_VERSION}"
        docker push "${APP_PACKAGES_URL}:latest"
        docker push "${APP_PACKAGES_URL}:${APP_VERSION}"
      env:
        APP_PACKAGES_URL: docker.pkg.github.com/${{ github.repository }}/container
        APP_PACKAGES_USERNAME: ${{ github.actor }}
        APP_PACKAGES_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
    - name: openapi
      run: |-
        gh release upload ${APP_TAG} --clobber ./target/openapi.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    runs-on: ubuntu-20.04
    needs:
    - build
    env:
      APP_VERSION: ${{ github.event.release.tag_name }}
    steps:
    - name: cf setup
      run: |-
        curl -L -o /tmp/cf.tgz "https://packages.cloudfoundry.org/stable?release=${CF_RELEASE}&version=${CF_VERSION}"
        tar -xzvf /tmp/cf.tgz -C /usr/local/bin && rm -f /tmp/cf.tgz
      env:
        CF_VERSION: 7.20.0
        CF_RELEASE: linux64-binary
    - name: cf push
      run: |-
        cf --version
